# Generated by Django 2.2 on 2019-04-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='location',
        ),
        migrations.AddField(
            model_name='song',
            name='song_name',
            field=models.CharField(default='song', max_length=30),
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.CharField(default='noone', max_length=30),
            preserve_default=False,
        ),
    ]
