# Generated by Django 2.2 on 2019-04-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab_api', '0002_auto_20190415_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_name',
            new_name='name',
        ),
    ]
